// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.normandieuniv.cpmnws.db;

import fr.normandieuniv.cpmnws.db.CpmnPerso;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect CpmnPerso_Roo_Jpa_Entity {
    
    declare @type: CpmnPerso: @Entity;
    
    declare @type: CpmnPerso: @Table(name = "V_NORMANDIE_LEOCARTE_PERSO");
    
}
