// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.normandieuniv.cpmnws.db;

import fr.normandieuniv.cpmnws.db.CpmnPerso;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CpmnPerso_Roo_Configurable {
    
    declare @type: CpmnPerso: @Configurable;
    
}
