// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.normandieuniv.cpmnws.web;

import fr.normandieuniv.cpmnws.db.CpmnPerso;
import fr.normandieuniv.cpmnws.web.CpmnPersoController;
import java.math.BigDecimal;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect CpmnPersoController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByAnneeUnivEquals", "form" }, method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsForm(Model uiModel) {
        return "cpmnpersos/findCpmnPersoesByAnneeUnivEquals";
    }
    
    @RequestMapping(params = "find=ByAnneeUnivEquals", method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEquals(@RequestParam("anneeUniv") BigDecimal anneeUniv, Model uiModel) {
        uiModel.addAttribute("cpmnpersoes", CpmnPerso.findCpmnPersoesByAnneeUnivEquals(anneeUniv).getResultList());
        return "cpmnpersos/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUnivEqualsAndNoIndividuEquals", "form" }, method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsForm(Model uiModel) {
        return "cpmnpersos/findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEquals";
    }
    
    @RequestMapping(params = "find=ByAnneeUnivEqualsAndNoIndividuEquals", method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEquals(@RequestParam("anneeUniv") BigDecimal anneeUniv, @RequestParam("noIndividu") BigDecimal noIndividu, Model uiModel) {
        uiModel.addAttribute("cpmnpersoes", CpmnPerso.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEquals(anneeUniv, noIndividu).getResultList());
        return "cpmnpersos/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUnivEqualsAndNoIndividuEqualsAndNomCarteLike", "form" }, method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsAndNomCarteLikeForm(Model uiModel) {
        return "cpmnpersos/findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsAndNomCarteLike";
    }
    
    @RequestMapping(params = "find=ByAnneeUnivEqualsAndNoIndividuEqualsAndNomCarteLike", method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsAndNomCarteLike(@RequestParam("anneeUniv") BigDecimal anneeUniv, @RequestParam("noIndividu") BigDecimal noIndividu, @RequestParam("nomCarte") String nomCarte, Model uiModel) {
        uiModel.addAttribute("cpmnpersoes", CpmnPerso.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsAndNomCarteLike(anneeUniv, noIndividu, nomCarte).getResultList());
        return "cpmnpersos/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUnivEqualsAndNoIndividuEqualsOrAnneeUnivEqualsAndNomCarteLike", "form" }, method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsOrAnneeUnivEqualsAndNomCarteLikeForm(Model uiModel) {
        return "cpmnpersos/findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsOrAnneeUnivEqualsAndNomCarteLike";
    }
    
    @RequestMapping(params = "find=ByAnneeUnivEqualsAndNoIndividuEqualsOrAnneeUnivEqualsAndNomCarteLike", method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsOrAnneeUnivEqualsAndNomCarteLike(@RequestParam("anneeUniv") BigDecimal anneeUniv, @RequestParam("noIndividu") BigDecimal noIndividu, @RequestParam("nomCarte") String nomCarte, Model uiModel) {
        uiModel.addAttribute("cpmnpersoes", CpmnPerso.findCpmnPersoesByAnneeUnivEqualsAndNoIndividuEqualsOrAnneeUnivEqualsAndNomCarteLike(anneeUniv, noIndividu, nomCarte).getResultList());
        return "cpmnpersos/list";
    }
    
    @RequestMapping(params = { "find=ByAnneeUnivEqualsAndNomCarteLike", "form" }, method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNomCarteLikeForm(Model uiModel) {
        return "cpmnpersos/findCpmnPersoesByAnneeUnivEqualsAndNomCarteLike";
    }
    
    @RequestMapping(params = "find=ByAnneeUnivEqualsAndNomCarteLike", method = RequestMethod.GET)
    public String CpmnPersoController.findCpmnPersoesByAnneeUnivEqualsAndNomCarteLike(@RequestParam("anneeUniv") BigDecimal anneeUniv, @RequestParam("nomCarte") String nomCarte, Model uiModel) {
        uiModel.addAttribute("cpmnpersoes", CpmnPerso.findCpmnPersoesByAnneeUnivEqualsAndNomCarteLike(anneeUniv, nomCarte).getResultList());
        return "cpmnpersos/list";
    }
    
}
